### ISSUE TITLE
Meetup Monkey - the idea

### ISSUE THREAD

**Issue by EAT-CODE-KITE-REPEAT** [EAT-CODE-KITE-REPEAT/meetup-monkey#1]
In Amsterdam, pursue going to 100 meetups in 2019. I'm a Meetup Monkey.

For just €4,95 a month (free first 6 months), this tool:

- Select all groups you're interested in within 50km from your location. This process takes ±15 minutes because there are a lot.
- Automatically join them if possible
- Get a weekly email on Sunday evening with all events in the next week. Button in the bottom to make a selection and add them to your own agenda.
- Option to automatically add all meetup events to your agenda by default. 
- Possibility to sort/filter by attendees before adding
- Every group has Outllink to communify.cc/createmeetupcommunity/meetupname to create community for meetup group and chat.

I think this can be done using their API. Simple website is all that's needed. 
This is an easy way to get immersed in some interests in Amsterdam, in many groups at once. Without using meetup app, just get them in your calendar. Much better!

MeetupMonkey.com ˜˜Ordered˜˜

A great landing page is key! Some great artistic logo would be epic. Use 99designs contest? What about a funny AD video with a guy in a monkey suit with the meetup logo on top, going to meetups every day :-) lol

This tool will be especially interesting for people that have used meetup in multiple cities, as meetup doesn't have filter capabilities. 

If it's not possible with the current API, do what I can, request additional access from meetup... Having a great story and landing page will also help :-) 

If I can onboard people in meetups to use MeetupMonkey to communify, and it gets traction, meetup may be interesting in buying it or collaborating. This is an interesting opportunity to get funding from the perfect partner: Meetup. They avg. ±1 million a month.

**Comment by EAT-CODE-KITE-REPEAT** [comment]
I created a definition of all functionality I think would be most useful. 
Events can be added automatically to your calendar after syncing with Cronofy

# Website:
## Frontpage
Meetup Monkey
Logo
'Automatically add Nearby Meetup Events to your Calendar'
[Login with Meetup] --> Sync with your calendar --> Get location --> Done!

## Preferences (?auth=...)
Change location

Your meetup groups in {city}:
* manage subs *

- [ ] Appsterdam (last event: social drinks)
- [x] Dev PHP (last event: meetup and talk)
- ......
.
.
.
[DELETE ACCOUNT] 

# Backend:
## Queries/Mutations:
* me(auth, lat?, lon?): { location, stats, nearbyMeetupsThisWeek { ...details, unsubscribed } }
* signup(meetupAuth,cronofyAuth,lat,lon): user
* deleteAccount(auth)

## Model:
* user { id, auth, meetupAuth, cronofyAuth, lat, lon, city, country, ...stats }
* unsubscribed { uid, meetupGroupId }

## Cron:
### Weekly mail: 
```
Hey {name}! We added {n} meetups to your calander for this week, in {city}:
* Appsterdam, monday 19:00 (180 going) [chat]
* Dev Entrepreneurs, tuesday 17:00 (20 going) [chat]
.......

[Edit preferences]

Cheers,
MeetupMonkey.com
````

### SubscriptionEndedMail
Hey Wijnand! Do you enjoy Meetup Monkey? Well, the free trial of 6 months has ended. Continue using it? Subscribe for 5$/month [PayPal]

**Comment by EAT-CODE-KITE-REPEAT** [comment]
# Todo (in this order)
- [ ] Go to Meetups and Startup Coworking spaces to pitch idea, get general opinion
- [ ] **Milestone 1** If I think I got product market fit enough, decide building it, otherwise re-imagine what stuff I can do with the API of Meetup. There must be something cool.
- [ ] Build model with GraphQLDefine, build backend boilerplate
- [ ] Create landing page as defined that signs up users to the service. Hire a designer for logo
- [ ] **Milestone 2** Test conversion on different Meetups, if it's high enough, build the rest
- [ ] Build weekly mail CRON
- [ ] Build preferences page with all mutations
- [ ] measure viral-factor in the weeks after by counting users vs. users I onboarded myself. If it gets traction, figure out a plan to get more traction
- [ ] Build PayPal or Stripe Subscription Integration and SubscriptionEndedEmail
- [ ] wait
- [ ] get a little rich
- [ ] show to meetup
- [ ] wait
- [ ] get bought, get real rich
